import { Injectable } from '@angular/core';
import { Iuser } from './iuser';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class UserData {
  private readonly userData: Iuser[] = [
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 1',
      image: 'assets/images/product1.jpg',
      price: 25,
      category: 1,
      date: '21sep 2025',
      inventoryStatus: 'unconfirmed',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 2,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 3,
      date: '21sep 2025',
      inventoryStatus: 'checkedout',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 4,
      date: '21sep 2025',
      inventoryStatus: 'unconfirmed',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 5,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'unconfirmed',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'unconfirmed',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'unconfirmed',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'unconfirmed',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedout',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedout',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'unconfirmed',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'unconfirmed',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
    {
      userRegDate: 'sep 15',
      userEmail: 'lorem@getMaxListeners.com',
      name: 'Product 2',
      image: 'assets/images/product2.jpg',
      price: 55,
      category: 6,
      date: '21sep 2025',
      inventoryStatus: 'checkedin',
      userRegTime: 'In 1 month → 10 night stay',
    },
  ];

  getuserDataMini(): Observable<Iuser[]> {
    return of(this.userData);
  }
}
